services:
  bikeapp-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bike_app
      MYSQL_USER: bikeappuser
      MYSQL_PASSWORD: bikeapppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    
  bikeapp-php:
    image: bikeapp-php:latest
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: always
    volumes:
      - .:/app
      - ./.docker/php/caddy.dev:/etc/caddy/Caddyfile
    labels:
    - dev.orbstack.domains=api.bikeapp.local
    networks:
      - backend
    command: ["sh", "-c", "frankenphp run --config /app/.docker/php/caddy.dev --adapter caddyfile --watch /app"]
  bikeapp-mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - backend
  vite:
    image: node:latest
    platform: linux/amd64
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev -- --host
    networks:
      - backend
    labels:
     - dev.orbstack.domains=vite.bikeapp.local
   

volumes:
  db_data:

networks:
  backend:
    driver: bridge
