// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://api.bikeapp.local' | (string & {});
};

/**
 * ActivityResource
 */
export type ActivityResource = {
    id: number;
    title: string;
    description: string;
    type: TypeActivityResource;
    typeFamily: TypeActivityFamily;
    dt_start: string;
    dt_end: string;
    notes: string;
    completedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
    recurrence: {
        frequency: string | null;
        interval: number | null;
    };
    shareUrl: string;
    distance?: number | null;
    duration?: number | null;
    avgSpeed?: number | null;
    maxSpeed?: number | null;
    waypoints?: Array<unknown> | null;
    startedAt?: string | null;
    stoppedAt?: string | null;
    trainingType?: 'interval' | 'endurance' | 'tempo' | 'recovery' | null;
    maintenanceType?: string | null;
    bike?: BikeResource | null;
    component?: ComponentsResource | null;
};

/**
 * BikeComponentsRequest
 */
export type BikeComponentsRequest = {
    model: string;
    type: Array<string>;
    status: number;
    multi_bike: boolean;
    type_id: number;
    brand_id: number;
};

/**
 * BikeResource
 */
export type BikeResource = {
    id: string;
    name: string;
    preferred: boolean;
    status: number;
    image: string;
    type: BikeTypeResource | null;
    stats: BikeStatsResource | null;
    components: Array<ComponentsResource> | null;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * BikeServiceResource
 */
export type BikeServiceResource = {
    id: string;
    method: string;
    intervalDistance: string;
    intervalTime: string;
    intervalRides: string;
    manualNote: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * BikeStatsResource
 */
export type BikeStatsResource = {
    id: string;
    distance: string;
    rides: string;
    lastService: string;
    service: BikeServiceResource | null;
    createdAt: string;
    updatedAt: string;
};

/**
 * BikeTypeResource
 */
export type BikeTypeResource = {
    id: string;
    label: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * ChallengeRequest
 */
export type ChallengeRequest = {
    title: string;
    description?: string | null;
    progress?: number | null;
    challenge_type: 'distance' | 'time' | 'speed';
    challenge_value: number;
    duration_challenge: number;
    is_daily_goal?: boolean | null;
    is_suggestion?: boolean | null;
    completed_at?: string | null;
};

/**
 * ChallengeResource
 */
export type ChallengeResource = {
    id: number;
    title: string;
    description: string | null;
    challengeType: string;
    challengeValue: number;
    progress: number;
    durationChallenge: number;
    isDailyGoal: boolean;
    isSuggestion: boolean;
    completedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * ComponentsBrand
 */
export type ComponentsBrand = {
    id: number;
    label: string;
};

/**
 * ComponentsResource
 */
export type ComponentsResource = {
    id: string;
    model: string;
    status: number;
    multiBike: string;
    type: {
        id: number;
        label: string;
    } | null;
    brand: {
        id: number;
        label: string;
    } | null;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * ComponentsType
 */
export type ComponentsType = {
    id: number;
    label: string;
};

/**
 * CreateActivityRequest
 */
export type CreateActivityRequest = {
    title: string;
    description?: string | null;
    dt_start: string;
    dt_end?: string | null;
    notes?: string | null;
    type_id: number;
    recurrence_frequency: 'daily' | 'weekly' | 'monthly' | 'yearly' | 'manually' | 'none';
    recurrence_interval?: number | null;
    class: 'App\\Models\\Activity\\Activity' | 'App\\Models\\Activity\\ActivityEvent' | 'App\\Models\\Activity\\ActivityMaintenance' | 'App\\Models\\Activity\\ActivityOther' | 'App\\Models\\Activity\\ActivityRide' | 'App\\Models\\Activity\\ActivityTraining';
};

/**
 * CreateBikeRequest
 */
export type CreateBikeRequest = {
    name: string;
    type_bike_id: number;
    preferred?: boolean;
    status?: number;
    image_url?: string | null;
    components?: Array<string>;
    stats: {
        distance?: number;
        rides?: number;
        last_service_date?: string | null;
        service: {
            method?: 'useLastServiceDate' | 'distanceInterval' | 'timeInterval' | 'ridesInterval' | 'manual' | 'none';
            interval_distance?: number;
            interval_time?: number;
            interval_rides?: number;
            manual_note?: string | null;
        };
    };
};

/**
 * NotificationResource
 */
export type NotificationResource = {
    id: string;
    suggestionType: string | 'social';
    title: string | null;
    subtitle: string | null;
    link: string | null;
    readAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * StatsItemResource
 */
export type StatsItemResource = {
    distance: string | number;
    duration: string | 0;
    rides: string | 0;
    goal: string | null;
};

/**
 * StatsResource
 */
export type StatsResource = {
    todayStats: StatsItemResource;
    weeklyStats: StatsItemResource;
    monthlyStats: StatsItemResource;
    totalStats: StatsItemResource;
};

/**
 * TypeActivityFamily
 */
export type TypeActivityFamily = 'ride' | 'maintenance' | 'event' | 'challenge' | 'training' | 'other';

/**
 * TypeActivityResource
 */
export type TypeActivityResource = {
    id: string;
    label: string;
    family: TypeActivityFamily;
    color: string;
    userId: string;
    isDefault: boolean;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * UpdateActivityRequest
 */
export type UpdateActivityRequest = {
    title?: string;
    description?: string | null;
    dt_start?: string | null;
    dt_end?: string | null;
    notes?: string | null;
    type_id?: number | null;
    started_at?: string | null;
    stopped_at?: string | null;
    recurrence_frequency?: 'daily' | 'weekly' | 'monthly' | 'yearly' | 'manually' | 'none';
    recurrence_interval?: number | null;
    completed_at?: string | null;
};

/**
 * UpdateUserRequest
 */
export type UpdateUserRequest = {
    email?: string;
    username?: string | null;
    first_name?: string | null;
    last_name?: string | null;
    picture?: string | null;
    phone_number?: string | null;
    birthday?: string | null;
    bio?: string | null;
    website?: string | null;
    language?: 'fr' | 'en';
    offline_mode?: boolean | null;
    notificationsPreferences?: {
        in_app_enabled?: boolean;
        email_enabled?: boolean;
        push_enabled?: boolean;
    };
};

/**
 * UserResource
 */
export type UserResource = {
    id: number;
    username: string;
    birthday: string | null;
    firstConnected: string | null;
    name: string | '';
    email: string;
    firstName: string;
    lastName: string;
    phone: string;
    avatarURL: string;
    bio: string;
    website: string;
    language: string;
    offlineMode: boolean | '';
    stats: StatsResource;
    createdAt: string | null;
    updatedAt: string | null;
    notifications: boolean;
    emailNotifications: boolean;
    pushNotifications: boolean;
};

export type GetUpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/up';
};

export type GetUpResponses = {
    200: string;
};

export type GetUpResponse = GetUpResponses[keyof GetUpResponses];

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '//';
};

export type GetResponses = {
    200: string;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type SuccessMessageData = {
    body: {
        name: string;
        email: string;
        subject: 'bug' | 'suggestion' | 'question' | 'autre';
        message: string;
    };
    path?: never;
    query?: never;
    url: '//';
};

export type SuccessMessageErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type SuccessMessageError = SuccessMessageErrors[keyof SuccessMessageErrors];

export type SuccessMessageResponses = {
    200: string;
};

export type SuccessMessageResponse = SuccessMessageResponses[keyof SuccessMessageResponses];

export type LangSwitchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/lang-switch';
};

export type LangSwitchResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type LangSwitchResponse = LangSwitchResponses[keyof LangSwitchResponses];

export type PrivacyPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/privacy-policy';
};

export type PrivacyPolicyResponses = {
    200: string;
};

export type PrivacyPolicyResponse = PrivacyPolicyResponses[keyof PrivacyPolicyResponses];

export type TermsOfServiceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/terms-of-service';
};

export type TermsOfServiceResponses = {
    200: string;
};

export type TermsOfServiceResponse = TermsOfServiceResponses[keyof TermsOfServiceResponses];

export type GetFirebaseTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/firebase-test';
};

export type GetFirebaseTestResponses = {
    200: 'Firebase test route';
};

export type GetFirebaseTestResponse = GetFirebaseTestResponses[keyof GetFirebaseTestResponses];

export type RedirectAppData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/redirect-app';
};

export type RedirectAppResponses = {
    200: string;
};

export type RedirectAppResponse = RedirectAppResponses[keyof RedirectAppResponses];

export type StorageLocalData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/storage/{path}';
};

export type StorageLocalResponses = {
    200: string;
};

export type StorageLocalResponse = StorageLocalResponses[keyof StorageLocalResponses];

export type StorageLocalUploadData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/storage/{path}';
};

export type StorageLocalUploadResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type StorageLocalUploadResponse = StorageLocalUploadResponses[keyof StorageLocalUploadResponses];

export type ActivitiesIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/activities';
};

export type ActivitiesIndexErrors = {
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ActivitiesIndexError = ActivitiesIndexErrors[keyof ActivitiesIndexErrors];

export type ActivitiesIndexResponses = {
    /**
     * Array of `ActivityResource`
     */
    200: Array<ActivityResource>;
};

export type ActivitiesIndexResponse = ActivitiesIndexResponses[keyof ActivitiesIndexResponses];

export type ActivitiesStoreData = {
    body: CreateActivityRequest;
    path?: never;
    query?: never;
    url: '/api/activities';
};

export type ActivitiesStoreErrors = {
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
    500: {
        message: 'Error creating activity';
        error: string;
    };
};

export type ActivitiesStoreError = ActivitiesStoreErrors[keyof ActivitiesStoreErrors];

export type ActivitiesStoreResponses = {
    /**
     * `ActivityResource`
     */
    200: ActivityResource;
};

export type ActivitiesStoreResponse = ActivitiesStoreResponses[keyof ActivitiesStoreResponses];

export type ActivitiesDestroyData = {
    body?: never;
    path: {
        /**
         * The activity ID
         */
        activity: number;
    };
    query?: never;
    url: '/api/activities/{activity}';
};

export type ActivitiesDestroyErrors = {
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ActivitiesDestroyError = ActivitiesDestroyErrors[keyof ActivitiesDestroyErrors];

export type ActivitiesDestroyResponses = {
    /**
     * No content
     */
    204: void;
};

export type ActivitiesDestroyResponse = ActivitiesDestroyResponses[keyof ActivitiesDestroyResponses];

export type ActivitiesShowData = {
    body?: never;
    path: {
        /**
         * The activity ID
         */
        activity: number;
    };
    query?: never;
    url: '/api/activities/{activity}';
};

export type ActivitiesShowErrors = {
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ActivitiesShowError = ActivitiesShowErrors[keyof ActivitiesShowErrors];

export type ActivitiesShowResponses = {
    /**
     * `ActivityResource`
     */
    200: ActivityResource;
};

export type ActivitiesShowResponse = ActivitiesShowResponses[keyof ActivitiesShowResponses];

export type ActivitiesUpdateData = {
    body?: UpdateActivityRequest;
    path: {
        /**
         * The activity ID
         */
        activity: number;
    };
    query?: never;
    url: '/api/activities/{activity}';
};

export type ActivitiesUpdateErrors = {
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ActivitiesUpdateError = ActivitiesUpdateErrors[keyof ActivitiesUpdateErrors];

export type ActivitiesUpdateResponses = {
    /**
     * `ActivityResource`
     */
    200: ActivityResource;
};

export type ActivitiesUpdateResponse = ActivitiesUpdateResponses[keyof ActivitiesUpdateResponses];

export type ActivityShareData = {
    body?: never;
    path: {
        /**
         * The activity ID
         */
        activity: number;
    };
    query?: never;
    url: '/api/activities/{activity}/share';
};

export type ActivityShareErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ActivityShareError = ActivityShareErrors[keyof ActivityShareErrors];

export type ActivityShareResponses = {
    200: {
        shareLink: string;
    };
};

export type ActivityShareResponse = ActivityShareResponses[keyof ActivityShareResponses];

export type ActivityOpenShareLinkData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/api/activities/share/{token}';
};

export type ActivityOpenShareLinkErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ActivityOpenShareLinkError = ActivityOpenShareLinkErrors[keyof ActivityOpenShareLinkErrors];

export type ActivityOpenShareLinkResponses = {
    /**
     * `ActivityResource`
     */
    200: ActivityResource;
};

export type ActivityOpenShareLinkResponse = ActivityOpenShareLinkResponses[keyof ActivityOpenShareLinkResponses];

export type TypesIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/activities/types';
};

export type TypesIndexResponses = {
    /**
     * Récupérer les types d'activités de l'utilisateur
     *
     *
     *
     * Array of `TypeActivityResource`
     */
    200: Array<TypeActivityResource>;
};

export type TypesIndexResponse = TypesIndexResponses[keyof TypesIndexResponses];

export type TypesStoreData = {
    body: {
        label: string;
        family: string;
        color?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/activities/types';
};

export type TypesStoreErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type TypesStoreError = TypesStoreErrors[keyof TypesStoreErrors];

export type TypesStoreResponses = {
    200: {
        message: 'Activity type created';
    };
};

export type TypesStoreResponse = TypesStoreResponses[keyof TypesStoreResponses];

export type TypesDestroyData = {
    body?: never;
    path: {
        /**
         * The type activity ID
         */
        typeActivity: number;
    };
    query?: never;
    url: '/api/activities/types/{typeActivity}';
};

export type TypesDestroyErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TypesDestroyError = TypesDestroyErrors[keyof TypesDestroyErrors];

export type TypesDestroyResponses = {
    200: {
        message: 'Activity type deleted';
    };
};

export type TypesDestroyResponse = TypesDestroyResponses[keyof TypesDestroyResponses];

export type TypesShowData = {
    body?: never;
    path: {
        /**
         * The type activity ID
         */
        typeActivity: number;
    };
    query?: never;
    url: '/api/activities/types/{typeActivity}';
};

export type TypesShowErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type TypesShowError = TypesShowErrors[keyof TypesShowErrors];

export type TypesShowResponses = {
    /**
     * `TypeActivityResource`
     */
    200: TypeActivityResource;
};

export type TypesShowResponse = TypesShowResponses[keyof TypesShowResponses];

export type TypesUpdateData = {
    body?: {
        label?: string;
        family?: string;
        color?: string | null;
    };
    path: {
        /**
         * The type activity ID
         */
        typeActivity: number;
    };
    query?: never;
    url: '/api/activities/types/{typeActivity}';
};

export type TypesUpdateErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type TypesUpdateError = TypesUpdateErrors[keyof TypesUpdateErrors];

export type TypesUpdateResponses = {
    /**
     * `TypeActivityResource`
     */
    200: TypeActivityResource;
};

export type TypesUpdateResponse = TypesUpdateResponses[keyof TypesUpdateResponses];

export type BikeGetTypeBikeIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bikes/types';
};

export type BikeGetTypeBikeIndexResponses = {
    /**
     * Array of `BikeTypeResource`
     */
    200: Array<BikeTypeResource>;
};

export type BikeGetTypeBikeIndexResponse = BikeGetTypeBikeIndexResponses[keyof BikeGetTypeBikeIndexResponses];

export type BikeGetTypeBikeShowData = {
    body?: never;
    path: {
        typeBike: string;
    };
    query?: never;
    url: '/api/bikes/types/{typeBike}';
};

export type BikeGetTypeBikeShowResponses = {
    /**
     * `BikeTypeResource`
     */
    200: BikeTypeResource;
};

export type BikeGetTypeBikeShowResponse = BikeGetTypeBikeShowResponses[keyof BikeGetTypeBikeShowResponses];

export type BikesIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bikes';
};

export type BikesIndexResponses = {
    /**
     * Array of `BikeResource`
     */
    200: Array<BikeResource>;
};

export type BikesIndexResponse = BikesIndexResponses[keyof BikesIndexResponses];

export type BikesStoreData = {
    body: CreateBikeRequest;
    path?: never;
    query?: never;
    url: '/api/bikes';
};

export type BikesStoreErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type BikesStoreError = BikesStoreErrors[keyof BikesStoreErrors];

export type BikesStoreResponses = {
    /**
     * `BikeResource`
     */
    200: BikeResource;
};

export type BikesStoreResponse = BikesStoreResponses[keyof BikesStoreResponses];

export type BikesDestroyData = {
    body?: never;
    path: {
        /**
         * The bike ID
         */
        bike: number;
    };
    query?: never;
    url: '/api/bikes/{bike}';
};

export type BikesDestroyErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type BikesDestroyError = BikesDestroyErrors[keyof BikesDestroyErrors];

export type BikesDestroyResponses = {
    200: {
        message: 'Bike deleted successfully';
        id: number;
    };
};

export type BikesDestroyResponse = BikesDestroyResponses[keyof BikesDestroyResponses];

export type BikesShowData = {
    body?: never;
    path: {
        /**
         * The bike ID
         */
        bike: number;
    };
    query?: never;
    url: '/api/bikes/{bike}';
};

export type BikesShowErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type BikesShowError = BikesShowErrors[keyof BikesShowErrors];

export type BikesShowResponses = {
    /**
     * `BikeResource`
     */
    200: BikeResource;
};

export type BikesShowResponse = BikesShowResponses[keyof BikesShowResponses];

export type BikesUpdateData = {
    body: CreateBikeRequest;
    path: {
        /**
         * The bike ID
         */
        bike: number;
    };
    query?: never;
    url: '/api/bikes/{bike}';
};

export type BikesUpdateErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type BikesUpdateError = BikesUpdateErrors[keyof BikesUpdateErrors];

export type BikesUpdateResponses = {
    /**
     * `BikeResource`
     */
    200: BikeResource;
};

export type BikesUpdateResponse = BikesUpdateResponses[keyof BikesUpdateResponses];

export type ChallengesIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/challenges';
};

export type ChallengesIndexResponses = {
    /**
     * Array of `ChallengeResource`
     */
    200: Array<ChallengeResource>;
};

export type ChallengesIndexResponse = ChallengesIndexResponses[keyof ChallengesIndexResponses];

export type ChallengesStoreData = {
    body: ChallengeRequest;
    path?: never;
    query?: never;
    url: '/api/challenges';
};

export type ChallengesStoreErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ChallengesStoreError = ChallengesStoreErrors[keyof ChallengesStoreErrors];

export type ChallengesStoreResponses = {
    /**
     * `ChallengeResource`
     */
    200: ChallengeResource;
};

export type ChallengesStoreResponse = ChallengesStoreResponses[keyof ChallengesStoreResponses];

export type ChallengesDestroyData = {
    body?: never;
    path: {
        /**
         * The challenge ID
         */
        challenge: number;
    };
    query?: never;
    url: '/api/challenges/{challenge}';
};

export type ChallengesDestroyErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ChallengesDestroyError = ChallengesDestroyErrors[keyof ChallengesDestroyErrors];

export type ChallengesDestroyResponses = {
    /**
     * No content
     */
    204: void;
};

export type ChallengesDestroyResponse = ChallengesDestroyResponses[keyof ChallengesDestroyResponses];

export type ChallengesShowData = {
    body?: never;
    path: {
        /**
         * The challenge ID
         */
        challenge: number;
    };
    query?: never;
    url: '/api/challenges/{challenge}';
};

export type ChallengesShowErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ChallengesShowError = ChallengesShowErrors[keyof ChallengesShowErrors];

export type ChallengesShowResponses = {
    /**
     * `ChallengeResource`
     */
    200: ChallengeResource;
};

export type ChallengesShowResponse = ChallengesShowResponses[keyof ChallengesShowResponses];

export type ChallengesUpdateData = {
    body: ChallengeRequest;
    path: {
        /**
         * The challenge ID
         */
        challenge: number;
    };
    query?: never;
    url: '/api/challenges/{challenge}';
};

export type ChallengesUpdateErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ChallengesUpdateError = ChallengesUpdateErrors[keyof ChallengesUpdateErrors];

export type ChallengesUpdateResponses = {
    /**
     * `ChallengeResource`
     */
    200: ChallengeResource;
};

export type ChallengesUpdateResponse = ChallengesUpdateResponses[keyof ChallengesUpdateResponses];

export type ComponentsBikeGetComponentsBrandIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bikes/components/brands';
};

export type ComponentsBikeGetComponentsBrandIndexResponses = {
    200: Array<ComponentsBrand>;
};

export type ComponentsBikeGetComponentsBrandIndexResponse = ComponentsBikeGetComponentsBrandIndexResponses[keyof ComponentsBikeGetComponentsBrandIndexResponses];

export type ComponentsBikeGetComponentsBrandShowData = {
    body?: never;
    path: {
        brand: string;
    };
    query?: never;
    url: '/api/bikes/components/brands/{brand}';
};

export type ComponentsBikeGetComponentsBrandShowResponses = {
    200: string;
};

export type ComponentsBikeGetComponentsBrandShowResponse = ComponentsBikeGetComponentsBrandShowResponses[keyof ComponentsBikeGetComponentsBrandShowResponses];

export type ComponentsBikeGetComponentsTypeIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bikes/components/types';
};

export type ComponentsBikeGetComponentsTypeIndexResponses = {
    200: Array<ComponentsType>;
};

export type ComponentsBikeGetComponentsTypeIndexResponse = ComponentsBikeGetComponentsTypeIndexResponses[keyof ComponentsBikeGetComponentsTypeIndexResponses];

export type ComponentsBikeGetComponentsTypeShowData = {
    body?: never;
    path: {
        type: string;
    };
    query?: never;
    url: '/api/bikes/components/types/{type}';
};

export type ComponentsBikeGetComponentsTypeShowResponses = {
    200: string;
};

export type ComponentsBikeGetComponentsTypeShowResponse = ComponentsBikeGetComponentsTypeShowResponses[keyof ComponentsBikeGetComponentsTypeShowResponses];

export type ComponentsIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bikes/components';
};

export type ComponentsIndexErrors = {
    401: {
        message: 'Unauthorized';
    };
};

export type ComponentsIndexError = ComponentsIndexErrors[keyof ComponentsIndexErrors];

export type ComponentsIndexResponses = {
    /**
     * Array of `ComponentsResource`
     */
    200: Array<ComponentsResource>;
};

export type ComponentsIndexResponse = ComponentsIndexResponses[keyof ComponentsIndexResponses];

export type ComponentsStoreData = {
    body: BikeComponentsRequest;
    path?: never;
    query?: never;
    url: '/api/bikes/components';
};

export type ComponentsStoreErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ComponentsStoreError = ComponentsStoreErrors[keyof ComponentsStoreErrors];

export type ComponentsStoreResponses = {
    /**
     * `ComponentsResource`
     */
    200: ComponentsResource;
};

export type ComponentsStoreResponse = ComponentsStoreResponses[keyof ComponentsStoreResponses];

export type ComponentsDestroyData = {
    body?: never;
    path: {
        /**
         * The component ID
         */
        component: number;
    };
    query?: never;
    url: '/api/bikes/components/{component}';
};

export type ComponentsDestroyErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    422: {
        message: 'Cannot delete component';
        errors: {
            multiBike: [
                string
            ];
        };
    };
};

export type ComponentsDestroyError = ComponentsDestroyErrors[keyof ComponentsDestroyErrors];

export type ComponentsDestroyResponses = {
    200: {
        message: 'ComponentsBikeController destroy method - deleted successfully';
        id: number;
    };
};

export type ComponentsDestroyResponse = ComponentsDestroyResponses[keyof ComponentsDestroyResponses];

export type ComponentsShowData = {
    body?: never;
    path: {
        /**
         * The component ID
         */
        component: number;
    };
    query?: never;
    url: '/api/bikes/components/{component}';
};

export type ComponentsShowErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ComponentsShowError = ComponentsShowErrors[keyof ComponentsShowErrors];

export type ComponentsShowResponses = {
    /**
     * `ComponentsResource`
     */
    200: ComponentsResource;
};

export type ComponentsShowResponse = ComponentsShowResponses[keyof ComponentsShowResponses];

export type ComponentsUpdateData = {
    body: BikeComponentsRequest;
    path: {
        /**
         * The component ID
         */
        component: number;
    };
    query?: never;
    url: '/api/bikes/components/{component}';
};

export type ComponentsUpdateErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ComponentsUpdateError = ComponentsUpdateErrors[keyof ComponentsUpdateErrors];

export type ComponentsUpdateResponses = {
    /**
     * `ComponentsResource`
     */
    200: ComponentsResource;
};

export type ComponentsUpdateResponse = ComponentsUpdateResponses[keyof ComponentsUpdateResponses];

export type ConfigWelcomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/assets/images/welcome-bg';
};

export type ConfigWelcomeResponses = {
    200: Array<unknown>;
};

export type ConfigWelcomeResponse = ConfigWelcomeResponses[keyof ConfigWelcomeResponses];

export type ConfigImageData = {
    body?: never;
    path: {
        filename: string;
    };
    query?: never;
    url: '/assets/images/onboarding/{filename}';
};

export type ConfigImageResponses = {
    200: Blob | File;
};

export type ConfigImageResponse = ConfigImageResponses[keyof ConfigImageResponses];

export type NotificationsIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications';
};

export type NotificationsIndexResponses = {
    /**
     * Array of `NotificationResource`
     */
    200: Array<NotificationResource>;
};

export type NotificationsIndexResponse = NotificationsIndexResponses[keyof NotificationsIndexResponses];

export type NotificationsDestroyData = {
    body?: never;
    path: {
        /**
         * The notification ID
         */
        notification: string;
    };
    query?: never;
    url: '/api/notifications/{notification}';
};

export type NotificationsDestroyErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type NotificationsDestroyError = NotificationsDestroyErrors[keyof NotificationsDestroyErrors];

export type NotificationsDestroyResponses = {
    /**
     * No content
     */
    204: void;
};

export type NotificationsDestroyResponse = NotificationsDestroyResponses[keyof NotificationsDestroyResponses];

export type NotificationsShowData = {
    body?: never;
    path: {
        /**
         * The notification ID
         */
        notification: string;
    };
    query?: never;
    url: '/api/notifications/{notification}';
};

export type NotificationsShowErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type NotificationsShowError = NotificationsShowErrors[keyof NotificationsShowErrors];

export type NotificationsShowResponses = {
    /**
     * `NotificationResource`
     */
    200: NotificationResource;
};

export type NotificationsShowResponse = NotificationsShowResponses[keyof NotificationsShowResponses];

export type NotificationsUpdateData = {
    body?: never;
    path: {
        /**
         * The notification ID
         */
        notification: string;
    };
    query?: never;
    url: '/api/notifications/{notification}';
};

export type NotificationsUpdateErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type NotificationsUpdateError = NotificationsUpdateErrors[keyof NotificationsUpdateErrors];

export type NotificationsUpdateResponses = {
    /**
     * `NotificationResource`
     */
    200: NotificationResource;
};

export type NotificationsUpdateResponse = NotificationsUpdateResponses[keyof NotificationsUpdateResponses];

export type UploadUploadData = {
    body: {
        file: string;
        ext: 'jpg' | 'jpeg' | 'png' | 'gif' | 'webp';
        type: 'bike' | 'ride' | 'component';
    };
    path?: never;
    query?: never;
    url: '/api/upload';
};

export type UploadUploadErrors = {
    /**
     * An error
     */
    413: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type UploadUploadError = UploadUploadErrors[keyof UploadUploadErrors];

export type UploadUploadResponses = {
    201: {
        path: string;
    };
};

export type UploadUploadResponse = UploadUploadResponses[keyof UploadUploadResponses];

export type UploadDownloadData = {
    body?: never;
    path: {
        /**
         * The user ID
         */
        user: number;
        path: string;
        filename: string;
    };
    query?: never;
    url: '/api/upload/{user}/{path}/{filename}';
};

export type UploadDownloadErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type UploadDownloadError = UploadDownloadErrors[keyof UploadDownloadErrors];

export type UploadDownloadResponses = {
    200: Blob | File;
};

export type UploadDownloadResponse = UploadDownloadResponses[keyof UploadDownloadResponses];

export type ProfileIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile';
};

export type ProfileIndexResponses = {
    /**
     * `UserResource`
     */
    200: UserResource;
};

export type ProfileIndexResponse = ProfileIndexResponses[keyof ProfileIndexResponses];

export type ProfileShowData = {
    body?: never;
    path: {
        /**
         * The user ID
         */
        user: number;
    };
    query?: never;
    url: '/api/profile/{user}';
};

export type ProfileShowErrors = {
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProfileShowError = ProfileShowErrors[keyof ProfileShowErrors];

export type ProfileShowResponses = {
    /**
     * `UserResource`
     */
    200: UserResource;
};

export type ProfileShowResponse = ProfileShowResponses[keyof ProfileShowResponses];

export type ProfileUpdateData = {
    body?: UpdateUserRequest;
    path: {
        /**
         * The user ID
         */
        user: number;
    };
    query?: never;
    url: '/api/profile/{user}';
};

export type ProfileUpdateErrors = {
    /**
     * Authorization error
     */
    403: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ProfileUpdateError = ProfileUpdateErrors[keyof ProfileUpdateErrors];

export type ProfileUpdateResponses = {
    /**
     * `UserResource`
     */
    200: UserResource;
};

export type ProfileUpdateResponse = ProfileUpdateResponses[keyof ProfileUpdateResponses];

export type UserForgetPasswordData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/forget-password';
};

export type UserForgetPasswordErrors = {
    404: {
        message: 'Si l\'email existe, un lien de réinitialisation du mot de passe a été envoyé.';
    };
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type UserForgetPasswordError = UserForgetPasswordErrors[keyof UserForgetPasswordErrors];

export type UserForgetPasswordResponses = {
    200: {
        message: 'Un lien de réinitialisation du mot de passe a été envoyé à votre email.';
    };
};

export type UserForgetPasswordResponse = UserForgetPasswordResponses[keyof UserForgetPasswordResponses];

export type LoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    405: {
        message: 'Please use POST method to login.';
    };
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type UserLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type UserLoginResponses = {
    200: {
        message: 'Login successful';
        user: UserResource;
    };
};

export type UserLoginResponse = UserLoginResponses[keyof UserLoginResponses];

export type UserLogoutData = {
    body?: {
        removeUser?: boolean;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type UserLogoutErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type UserLogoutError = UserLogoutErrors[keyof UserLogoutErrors];

export type UserLogoutResponses = {
    200: {
        message: 'Logout successful';
    } | {
        message: 'User removed successfully';
    };
};

export type UserLogoutResponse = UserLogoutResponses[keyof UserLogoutResponses];
