// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * BikeComponentsRequest
 */
export const zBikeComponentsRequest = z.object({
    model: z.string(),
    type: z.array(z.string()).min(1),
    status: z.int().gte(0).lte(100),
    multi_bike: z.boolean(),
    type_id: z.int(),
    brand_id: z.int()
});

/**
 * BikeServiceResource
 */
export const zBikeServiceResource = z.object({
    id: z.string(),
    method: z.string(),
    intervalDistance: z.string(),
    intervalTime: z.string(),
    intervalRides: z.string(),
    manualNote: z.string(),
    createdAt: z.string(),
    updatedAt: z.string()
});

/**
 * BikeStatsResource
 */
export const zBikeStatsResource = z.object({
    id: z.string(),
    distance: z.string(),
    rides: z.string(),
    lastService: z.string(),
    service: zBikeServiceResource.nullable(),
    createdAt: z.string(),
    updatedAt: z.string()
});

/**
 * BikeTypeResource
 */
export const zBikeTypeResource = z.object({
    id: z.string(),
    label: z.string(),
    createdAt: z.string(),
    updatedAt: z.string()
});

/**
 * ChallengeRequest
 */
export const zChallengeRequest = z.object({
    title: z.string().max(255),
    description: z.string().nullish(),
    progress: z.number().gte(0).nullish(),
    challenge_type: z.enum([
        'distance',
        'time',
        'speed'
    ]),
    challenge_value: z.number(),
    duration_challenge: z.int(),
    is_daily_goal: z.boolean().nullish(),
    is_suggestion: z.boolean().nullish(),
    completed_at: z.iso.datetime().nullish()
});

/**
 * ChallengeResource
 */
export const zChallengeResource = z.object({
    id: z.int(),
    title: z.string(),
    description: z.string().nullable(),
    challengeType: z.string(),
    challengeValue: z.int(),
    progress: z.int(),
    durationChallenge: z.int(),
    isDailyGoal: z.boolean(),
    isSuggestion: z.boolean(),
    completedAt: z.iso.datetime().nullable(),
    createdAt: z.iso.datetime().nullable(),
    updatedAt: z.iso.datetime().nullable()
});

/**
 * ComponentsBrand
 */
export const zComponentsBrand = z.object({
    id: z.int(),
    label: z.string()
});

/**
 * ComponentsResource
 */
export const zComponentsResource = z.object({
    id: z.string(),
    model: z.string(),
    status: z.int(),
    multiBike: z.string(),
    type: z.object({
        id: z.int(),
        label: z.string()
    }).nullable(),
    brand: z.object({
        id: z.int(),
        label: z.string()
    }).nullable(),
    createdAt: z.string().nullable(),
    updatedAt: z.string().nullable()
});

/**
 * BikeResource
 */
export const zBikeResource = z.object({
    id: z.string(),
    name: z.string(),
    preferred: z.boolean(),
    status: z.int(),
    image: z.string(),
    type: zBikeTypeResource.nullable(),
    stats: zBikeStatsResource.nullable(),
    components: z.array(zComponentsResource).nullable(),
    createdAt: z.string().nullable(),
    updatedAt: z.string().nullable()
});

/**
 * ComponentsType
 */
export const zComponentsType = z.object({
    id: z.int(),
    label: z.string()
});

/**
 * CreateActivityRequest
 */
export const zCreateActivityRequest = z.object({
    title: z.string().max(255),
    description: z.string().nullish(),
    dt_start: z.iso.datetime(),
    dt_end: z.iso.datetime().nullish(),
    notes: z.string().nullish(),
    type_id: z.int(),
    recurrence_frequency: z.enum([
        'daily',
        'weekly',
        'monthly',
        'yearly',
        'manually',
        'none'
    ]),
    recurrence_interval: z.int().gte(0).nullish(),
    class: z.enum([
        'App\\Models\\Activity\\Activity',
        'App\\Models\\Activity\\ActivityEvent',
        'App\\Models\\Activity\\ActivityMaintenance',
        'App\\Models\\Activity\\ActivityOther',
        'App\\Models\\Activity\\ActivityRide',
        'App\\Models\\Activity\\ActivityTraining'
    ])
});

/**
 * CreateBikeRequest
 */
export const zCreateBikeRequest = z.object({
    name: z.string().max(255),
    type_bike_id: z.int(),
    preferred: z.boolean().optional(),
    status: z.int().gte(0).lte(100).optional(),
    image_url: z.string().max(255).nullish(),
    components: z.array(z.string()).optional(),
    stats: z.object({
        distance: z.number().gte(0).optional(),
        rides: z.number().gte(0).optional(),
        last_service_date: z.iso.datetime().nullish(),
        service: z.object({
            method: z.enum([
                'useLastServiceDate',
                'distanceInterval',
                'timeInterval',
                'ridesInterval',
                'manual',
                'none'
            ]).optional(),
            interval_distance: z.number().gte(0).optional(),
            interval_time: z.number().gte(0).optional(),
            interval_rides: z.number().gte(0).optional(),
            manual_note: z.string().nullish()
        })
    })
});

/**
 * NotificationResource
 */
export const zNotificationResource = z.object({
    id: z.string(),
    suggestionType: z.union([
        z.string(),
        z.enum(['social'])
    ]),
    title: z.string().nullable(),
    subtitle: z.string().nullable(),
    link: z.string().nullable(),
    readAt: z.string().nullable(),
    createdAt: z.string().nullable(),
    updatedAt: z.string().nullable()
});

/**
 * StatsItemResource
 */
export const zStatsItemResource = z.object({
    distance: z.union([
        z.string(),
        z.number()
    ]),
    duration: z.union([
        z.string(),
        z.literal(0)
    ]),
    rides: z.union([
        z.string(),
        z.literal(0)
    ]),
    goal: z.string().nullable()
});

/**
 * StatsResource
 */
export const zStatsResource = z.object({
    todayStats: zStatsItemResource,
    weeklyStats: zStatsItemResource,
    monthlyStats: zStatsItemResource,
    totalStats: zStatsItemResource
});

/**
 * TypeActivityFamily
 */
export const zTypeActivityFamily = z.enum([
    'ride',
    'maintenance',
    'event',
    'challenge',
    'training',
    'other'
]);

/**
 * TypeActivityResource
 */
export const zTypeActivityResource = z.object({
    id: z.string(),
    label: z.string(),
    family: zTypeActivityFamily,
    color: z.string(),
    userId: z.string(),
    isDefault: z.boolean(),
    createdAt: z.string().nullable(),
    updatedAt: z.string().nullable()
});

/**
 * ActivityResource
 */
export const zActivityResource = z.object({
    id: z.int(),
    title: z.string(),
    description: z.string(),
    type: zTypeActivityResource,
    typeFamily: zTypeActivityFamily,
    dt_start: z.string(),
    dt_end: z.string(),
    notes: z.string(),
    completedAt: z.string().nullable(),
    createdAt: z.string().nullable(),
    updatedAt: z.string().nullable(),
    recurrence: z.object({
        frequency: z.string().nullable(),
        interval: z.int().nullable()
    }),
    shareUrl: z.string(),
    distance: z.number().nullish(),
    duration: z.int().nullish(),
    avgSpeed: z.number().nullish(),
    maxSpeed: z.number().nullish(),
    waypoints: z.array(z.unknown()).nullish(),
    startedAt: z.string().nullish(),
    stoppedAt: z.string().nullish(),
    trainingType: z.enum([
        'interval',
        'endurance',
        'tempo',
        'recovery'
    ]).nullish(),
    maintenanceType: z.string().nullish(),
    bike: zBikeResource.nullish(),
    component: zComponentsResource.nullish()
});

/**
 * UpdateActivityRequest
 */
export const zUpdateActivityRequest = z.object({
    title: z.string().max(255).optional(),
    description: z.string().nullish(),
    dt_start: z.iso.datetime().nullish(),
    dt_end: z.iso.datetime().nullish(),
    notes: z.string().nullish(),
    type_id: z.int().nullish(),
    started_at: z.iso.datetime().nullish(),
    stopped_at: z.iso.datetime().nullish(),
    recurrence_frequency: z.enum([
        'daily',
        'weekly',
        'monthly',
        'yearly',
        'manually',
        'none'
    ]).optional(),
    recurrence_interval: z.int().gte(0).nullish(),
    completed_at: z.iso.datetime().nullish()
});

/**
 * UpdateUserRequest
 */
export const zUpdateUserRequest = z.object({
    email: z.email().optional(),
    username: z.string().max(255).nullish(),
    first_name: z.string().max(255).nullish(),
    last_name: z.string().max(255).nullish(),
    picture: z.url().nullish(),
    phone_number: z.string().max(20).nullish(),
    birthday: z.iso.date().nullish(),
    bio: z.string().max(500).nullish(),
    website: z.url().nullish(),
    language: z.enum(['fr', 'en']).optional(),
    offline_mode: z.boolean().nullish(),
    notificationsPreferences: z.object({
        in_app_enabled: z.boolean().optional(),
        email_enabled: z.boolean().optional(),
        push_enabled: z.boolean().optional()
    }).optional()
});

/**
 * UserResource
 */
export const zUserResource = z.object({
    id: z.int(),
    username: z.string(),
    birthday: z.string().nullable(),
    firstConnected: z.iso.datetime().nullable(),
    name: z.union([
        z.string(),
        z.enum([''])
    ]),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    phone: z.string(),
    avatarURL: z.string(),
    bio: z.string(),
    website: z.string(),
    language: z.string(),
    offlineMode: z.union([
        z.boolean(),
        z.enum([''])
    ]),
    stats: zStatsResource,
    createdAt: z.iso.datetime().nullable(),
    updatedAt: z.iso.datetime().nullable(),
    notifications: z.boolean(),
    emailNotifications: z.boolean(),
    pushNotifications: z.boolean()
});

export const zGetUpResponse = z.string();

export const zGetResponse = z.string();

export const zSuccessMessageBody = z.object({
    name: z.string().min(2).max(255),
    email: z.email().max(255),
    subject: z.enum([
        'bug',
        'suggestion',
        'question',
        'autre'
    ]),
    message: z.string().max(1000)
});

export const zSuccessMessageResponse = z.string();

export const zLangSwitchResponse = z.record(z.string(), z.unknown());

export const zPrivacyPolicyResponse = z.string();

export const zTermsOfServiceResponse = z.string();

export const zGetFirebaseTestResponse = z.literal('Firebase test route');

export const zRedirectAppResponse = z.string();

export const zStorageLocalPath = z.object({
    path: z.string()
});

export const zStorageLocalResponse = z.string();

export const zStorageLocalUploadPath = z.object({
    path: z.string()
});

export const zStorageLocalUploadResponse = z.record(z.string(), z.unknown());

/**
 * Array of `ActivityResource`
 */
export const zActivitiesIndexResponse = z.array(zActivityResource);

export const zActivitiesStoreBody = zCreateActivityRequest;

/**
 * `ActivityResource`
 */
export const zActivitiesStoreResponse = zActivityResource;

export const zActivitiesDestroyPath = z.object({
    activity: z.int()
});

/**
 * No content
 */
export const zActivitiesDestroyResponse = z.void();

export const zActivitiesShowPath = z.object({
    activity: z.int()
});

/**
 * `ActivityResource`
 */
export const zActivitiesShowResponse = zActivityResource;

export const zActivitiesUpdateBody = zUpdateActivityRequest;

export const zActivitiesUpdatePath = z.object({
    activity: z.int()
});

/**
 * `ActivityResource`
 */
export const zActivitiesUpdateResponse = zActivityResource;

export const zActivitySharePath = z.object({
    activity: z.int()
});

export const zActivityShareResponse = z.object({
    shareLink: z.string()
});

export const zActivityOpenShareLinkPath = z.object({
    token: z.string()
});

/**
 * `ActivityResource`
 */
export const zActivityOpenShareLinkResponse = zActivityResource;

/**
 * Récupérer les types d'activités de l'utilisateur
 *
 *
 *
 * Array of `TypeActivityResource`
 */
export const zTypesIndexResponse = z.array(zTypeActivityResource);

export const zTypesStoreBody = z.object({
    label: z.string().max(255),
    family: z.string().max(255),
    color: z.string().nullish()
});

export const zTypesStoreResponse = z.object({
    message: z.literal('Activity type created')
});

export const zTypesDestroyPath = z.object({
    typeActivity: z.int()
});

export const zTypesDestroyResponse = z.object({
    message: z.literal('Activity type deleted')
});

export const zTypesShowPath = z.object({
    typeActivity: z.int()
});

/**
 * `TypeActivityResource`
 */
export const zTypesShowResponse = zTypeActivityResource;

export const zTypesUpdateBody = z.object({
    label: z.string().max(255).optional(),
    family: z.string().max(255).optional(),
    color: z.string().nullish()
});

export const zTypesUpdatePath = z.object({
    typeActivity: z.int()
});

/**
 * `TypeActivityResource`
 */
export const zTypesUpdateResponse = zTypeActivityResource;

/**
 * Array of `BikeTypeResource`
 */
export const zBikeGetTypeBikeIndexResponse = z.array(zBikeTypeResource);

export const zBikeGetTypeBikeShowPath = z.object({
    typeBike: z.string()
});

/**
 * `BikeTypeResource`
 */
export const zBikeGetTypeBikeShowResponse = zBikeTypeResource;

/**
 * Array of `BikeResource`
 */
export const zBikesIndexResponse = z.array(zBikeResource);

export const zBikesStoreBody = zCreateBikeRequest;

/**
 * `BikeResource`
 */
export const zBikesStoreResponse = zBikeResource;

export const zBikesDestroyPath = z.object({
    bike: z.int()
});

export const zBikesDestroyResponse = z.object({
    message: z.literal('Bike deleted successfully'),
    id: z.int()
});

export const zBikesShowPath = z.object({
    bike: z.int()
});

/**
 * `BikeResource`
 */
export const zBikesShowResponse = zBikeResource;

export const zBikesUpdateBody = zCreateBikeRequest;

export const zBikesUpdatePath = z.object({
    bike: z.int()
});

/**
 * `BikeResource`
 */
export const zBikesUpdateResponse = zBikeResource;

/**
 * Array of `ChallengeResource`
 */
export const zChallengesIndexResponse = z.array(zChallengeResource);

export const zChallengesStoreBody = zChallengeRequest;

/**
 * `ChallengeResource`
 */
export const zChallengesStoreResponse = zChallengeResource;

export const zChallengesDestroyPath = z.object({
    challenge: z.int()
});

/**
 * No content
 */
export const zChallengesDestroyResponse = z.void();

export const zChallengesShowPath = z.object({
    challenge: z.int()
});

/**
 * `ChallengeResource`
 */
export const zChallengesShowResponse = zChallengeResource;

export const zChallengesUpdateBody = zChallengeRequest;

export const zChallengesUpdatePath = z.object({
    challenge: z.int()
});

/**
 * `ChallengeResource`
 */
export const zChallengesUpdateResponse = zChallengeResource;

export const zComponentsBikeGetComponentsBrandIndexResponse = z.array(zComponentsBrand);

export const zComponentsBikeGetComponentsBrandShowPath = z.object({
    brand: z.string()
});

export const zComponentsBikeGetComponentsBrandShowResponse = z.string();

export const zComponentsBikeGetComponentsTypeIndexResponse = z.array(zComponentsType);

export const zComponentsBikeGetComponentsTypeShowPath = z.object({
    type: z.string()
});

export const zComponentsBikeGetComponentsTypeShowResponse = z.string();

/**
 * Array of `ComponentsResource`
 */
export const zComponentsIndexResponse = z.array(zComponentsResource);

export const zComponentsStoreBody = zBikeComponentsRequest;

/**
 * `ComponentsResource`
 */
export const zComponentsStoreResponse = zComponentsResource;

export const zComponentsDestroyPath = z.object({
    component: z.int()
});

export const zComponentsDestroyResponse = z.object({
    message: z.literal('ComponentsBikeController destroy method - deleted successfully'),
    id: z.int()
});

export const zComponentsShowPath = z.object({
    component: z.int()
});

/**
 * `ComponentsResource`
 */
export const zComponentsShowResponse = zComponentsResource;

export const zComponentsUpdateBody = zBikeComponentsRequest;

export const zComponentsUpdatePath = z.object({
    component: z.int()
});

/**
 * `ComponentsResource`
 */
export const zComponentsUpdateResponse = zComponentsResource;

export const zConfigWelcomeResponse = z.array(z.unknown());

export const zConfigImagePath = z.object({
    filename: z.string()
});

export const zConfigImageResponse = z.string();

/**
 * Array of `NotificationResource`
 */
export const zNotificationsIndexResponse = z.array(zNotificationResource);

export const zNotificationsDestroyPath = z.object({
    notification: z.string()
});

/**
 * No content
 */
export const zNotificationsDestroyResponse = z.void();

export const zNotificationsShowPath = z.object({
    notification: z.string()
});

/**
 * `NotificationResource`
 */
export const zNotificationsShowResponse = zNotificationResource;

export const zNotificationsUpdatePath = z.object({
    notification: z.string()
});

/**
 * `NotificationResource`
 */
export const zNotificationsUpdateResponse = zNotificationResource;

export const zUploadUploadBody = z.object({
    file: z.string(),
    ext: z.enum([
        'jpg',
        'jpeg',
        'png',
        'gif',
        'webp'
    ]),
    type: z.enum([
        'bike',
        'ride',
        'component'
    ])
});

export const zUploadUploadResponse = z.object({
    path: z.string()
});

export const zUploadDownloadPath = z.object({
    user: z.int(),
    path: z.string(),
    filename: z.string()
});

export const zUploadDownloadResponse = z.string();

/**
 * `UserResource`
 */
export const zProfileIndexResponse = zUserResource;

export const zProfileShowPath = z.object({
    user: z.int()
});

/**
 * `UserResource`
 */
export const zProfileShowResponse = zUserResource;

export const zProfileUpdateBody = zUpdateUserRequest;

export const zProfileUpdatePath = z.object({
    user: z.int()
});

/**
 * `UserResource`
 */
export const zProfileUpdateResponse = zUserResource;

export const zUserForgetPasswordBody = z.object({
    email: z.email()
});

export const zUserForgetPasswordResponse = z.object({
    message: z.literal('Un lien de réinitialisation du mot de passe a été envoyé à votre email.')
});

export const zUserLoginResponse = z.object({
    message: z.literal('Login successful'),
    user: zUserResource
});

export const zUserLogoutBody = z.object({
    removeUser: z.boolean().optional()
});

export const zUserLogoutResponse = z.union([
    z.object({
        message: z.literal('Logout successful')
    }),
    z.object({
        message: z.literal('User removed successfully')
    })
]);
